[workspace]
authors = ["Carsonkoffler <ckoffler@ucsd.edu>"]
channels = ["conda-forge"]
name = "rentzsch2015"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
r-base = ">=4.5.1,<4.6"
r-rmarkdown = ">=2.30,<3"
r-quarto = ">=1.5.1,<2"
r-knitr = ">=1.50,<2"
