---
title: "Replication of Study 5 by Rentzsch & Gross (2015, European Journal of Personality)"
author: "Carson Koffler (ckoffler@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---



<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

I have chosen to replicate Rentzsch and Gross’ (2015) work on looking at dispositional envy on state envy in didactic interactions (study 5). For my first year project, I am interested in studying the methods used to elicit envy to examine if they are truly eliciting what they claim to be (i.e., is this method making you envious or another corollary negative emotion). In refining envy manipulations, we can 1) better understand the boundaries between envy and other negative emotions and 2) make sure we are truly measuring what we intend to measure. Rentzsch and Gross in this study use the classic game - Rock, Paper, Scissors - to measure envy of the advantaged and disadvantaged players. Replicating this study will give us more information about different methods available to our lab for future envy research. Additionally, I can gain insight on the feasibility for this method online, as that is the primary research method our lab uses. 

This study was originally an in-person experiment, but for the purposes of this replication, I will transfer this design to being online with the understanding that this will provide evidence for a conceptual replication rather than a direct replication. The procedures are as follows (Note: since this is online, some of the procedures are different than the original): 
  The participants will type in their name or a psuedonym to be applied to the game avatar and be introduced to the other player (an unbeknownst computerized player). The participants will be provided the rules to the rock-paper-scissors game and allowed to play three practice rounds. After practicing, they will play one round for a prize -- an additional monetary incentive (this was done in the 2023 version of the study). Participants will be placed in two conditions: High envy (Lost) and low envy (Won). The games will be coded to ensure that those in the high envy condition lose the last round and those in the low envy win the last round. To mirror the original study, I will have a virtual scoreboard present throughout the study that shows the winner and loser of the game and their monetary standings. Following the game, the participants will complete a short semantic categorization task as a distractor task (Patel et al., 1997). Then, they will fill out various measures to analyze their dispositional envy (using the DSES measure), social desirability (using BIDR measure), their state emotions (*"I am a little jealous of that person", "I envy the other person."*), thoughts about the attributes of the game [i.e., their skill, their luck, the task difficulty, their ability/effort(*"The outcome of the situation was unjust.", "The outcome of the situation was uncontrollable."*)], and whether or not they thought they could have won the game (*"What do you attribute your result in the rock-paper-scissors game to?"*). All of these measures are scaled on a 7-point Likert scale other than the attribution of the outcome measure which is a 4-option forced choice scale. Throughout the survey, there will be deliberate attention/comprehension checks and the semantic categorization task will also act as an attention check. All of the categories laid out are very simple and easy, so if participants get them all wrong, I can suspect that they are not engaging with the material. After all of the measures, the participants will be debriefed about the deception and given an equal amount as those in the low envy condition (i.e., those who won the game).  


This study should require around 68 participants. There was a medium to large effect size (*d*=0.68), so with an alpha of 0.05 and beta of 0.80, a reasonable sample size would be 68. While I have not completely coded up the survey yet to fully test the amount of time it would take to complete the study, I would estimate it should take around 15 minutes to complete the game and all of the measures.  

**Notes**: 
1) The monetary incentive in the 2023 study was 10 euros, but I don't think we need to use that steep of a prize. In the past, Mike has used a dollar or so and was still able to find envy responses. Can we discuss the size of this amount once we have a better idea of the course's funds?  

2) The measures can be found in the supplemental materials of a later study that used this method (Rentzsch et al., 2023). The 2023 study included more measures than the 2015 study I am replicating. I will double check with the Rentzsch, but the measures used in the 2015 should be found on tables 7 (DSES), 14 (BIDR), 27 (state emotions), 32 (appraisals about the situation), 37 (attribution of the outcome)

3) The semantic categorization task was not explicitly shown in the procedures, so I am going to create a very simple semantic categorization task using the word list from Patel, Bullinaria & Levy (1997). (information can also be found here: https://johnbullinaria.github.io/corpus.html )

Rentzsch, K., Giese, A.-K., Hebel, V., & Lösch, T. (2023). Personality and Emotions in Social Interactions – the PESI project. *Personality Science*, 4, 1-15. https://doi.org/10.5964/ps.8241

Patel, M., Bullinaria, J. A., & Levy, J. P. (1997). Extracting semantic representations from large text corpora. In J. A. Bullinaria, D. W.
Glasspool, & G. Houghton (Eds.), Fourth Neural Computation and Psychology Workshop: Connectionist Representations (pp. 199-212). London: Springer.


## Methods
I will be replicating study 5 in Rentzsch and Gross's (2015) study that analyzes state envy following a social interaction. 

The only inclusion criteria for this study will be fluency in English. The data collected from participants will be basic demographics, age and gender, and responses to the following scales -- dispositional envy (using the DSES measure), social desirability (using BIDR measure), their state emotions, appraisals of the situation, and outcome attribution. Other than the outcome attribution measure which is a 4-point scale, all other data uses a 7-point likert scale. Participants with missing data on key variables or who fail attention checks will be excluded. Scale scores (DSES, BIDR, state emotions, appraisals, outcome attributions) will be computed as the median of the corresponding items after reverse coding where applicable. The manipulation variable will be dummy coded: 0 = winner (low envy condition), 1 = loser (high envy condition).

The main confirmatory test will be an independent-samples t-test comparing state envy between winners and losers. This directly tests the hypothesis that people will envy those who receive a reward when they do not, consistent with the original study. Assumptions of normality and homogeneity of variances will be checked before analysis.

Original findings: participants who lost (did not receive reward) reported higher envy (*M* = 2.00, *SD* = 1.08) than winners (received reward) (*M* = 1.31, *SD* = 0.89), *t*(57) = 2.67, *p* = 0.01. Successful replication would reproduce this effect in the same direction and similar magnitude.


### Reliability and Validity 
What is the key construct?  

The key construct measured is envy.
        
What is the measure?  

Envy is being measured with an Emotional Experiences scale (Rentzsch & Gross, 2015). They have other variables being evaluated using different measures, but this is the measure that the state envy analysis relies on.
     
Is any reliability evidence shared or cited? Do they mention reliability?

Reliability for the measures was shared using Chronbach's alpha. This measure assesses the internal reliability of items within the scales. All αs > 0.62 showing that there was a large internal reliability of items within the scales.
     
Is any validity evidence shared or cited? What sort of validity?

This task was shown to have external validity on increasing envy through convergent validity. State envy increases for losers of the game correlated strongly with dispositional envy. This means that those who have higher rates of envy on average had increases in envy following the loss in the game. 



### Power Analysis

There was a medium to large effect size (*d*=0.70), so with an alpha of 0.05 and power of 0.80, a reasonable sample size would be **around 66-68**. This should be feasible unless there are large funding constraints. 

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
